<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductionOutputsSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('production_outputs')->truncate();

        $now = Carbon::now();

        DB::table('production_outputs')->insert([
            // 1
            [
                'id' => 1,
                'product_name' => '350ml',
                'quantity' => 25,
                'qty_350ml' => 25,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251103-167',
                'production_date' => '2025-11-03 00:00:00+08',
                'quantity_pcs' => 25,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 25,
                    'Blue Plastic Cap' => 25,
                    'Label' => 25,
                    'Stretchfilm' => 25,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E02501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 2
            [
                'id' => 2,
                'product_name' => '350ml',
                'quantity' => 24,
                'qty_350ml' => 24,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251104-194',
                'production_date' => '2025-11-04 00:00:00+08',
                'quantity_pcs' => 24,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 24,
                    'Blue Plastic Cap' => 24,
                    'Label' => 24,
                    'Stretchfilm' => 24,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 3
            [
                'id' => 3,
                'product_name' => '350ml',
                'quantity' => 1,
                'qty_350ml' => 1,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251104-681',
                'production_date' => '2025-11-05 00:00:00+08',
                'quantity_pcs' => 1,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 1,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 4
            [
                'id' => 4,
                'product_name' => '350ml',
                'quantity' => 12,
                'qty_350ml' => 12,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251104-682',
                'production_date' => '2025-11-05 00:00:00+08',
                'quantity_pcs' => 12,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 12,
                    'Blue Plastic Cap' => 12,
                    'Label' => 12,
                    'Stretchfilm' => 12,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 5
            [
                'id' => 5,
                'product_name' => '350ml',
                'quantity' => 1,
                'qty_350ml' => 1,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251105-618',
                'production_date' => '2025-11-05 00:00:00+08',
                'quantity_pcs' => 1,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 1,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 6
            [
                'id' => 6,
                'product_name' => '350ml',
                'quantity' => 1,
                'qty_350ml' => 1,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251108-442',
                'production_date' => '2025-11-08 00:00:00+08',
                'quantity_pcs' => 1,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 1,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 7
            [
                'id' => 7,
                'product_name' => '350ml',
                'quantity' => 2,
                'qty_350ml' => 2,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-132',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 2,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 2,
                    'Blue Plastic Cap' => 2,
                    'Label' => 2,
                    'Stretchfilm' => 2,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 8
            [
                'id' => 8,
                'product_name' => '350ml',
                'quantity' => 5,
                'qty_350ml' => 5,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-621',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 5,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 5,
                    'Blue Plastic Cap' => 5,
                    'Label' => 5,
                    'Stretchfilm' => 5,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 9
            [
                'id' => 9,
                'product_name' => '350ml',
                'quantity' => 5,
                'qty_350ml' => 5,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-181',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 5,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 5,
                    'Blue Plastic Cap' => 5,
                    'Label' => 5,
                    'Stretchfilm' => 5,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 10
            [
                'id' => 10,
                'product_name' => '1L',
                'quantity' => 200,
                'qty_350ml' => 0,
                'qty_500ml' => 0,
                'qty_1l' => 200,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-614',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 200,
                'materials_needed' => json_encode([
                    'Plastic Bottle (1L)' => 200,
                    'Blue Plastic Cap' => 200,
                    'Label' => 200,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (1L)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 11
            [
                'id' => 11,
                'product_name' => '350ml',
                'quantity' => 4,
                'qty_350ml' => 4,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-185',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 4,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 4,
                    'Blue Plastic Cap' => 4,
                    'Label' => 4,
                    'Stretchfilm' => 4,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 12
            [
                'id' => 12,
                'product_name' => '350ml',
                'quantity' => 2,
                'qty_350ml' => 2,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-879',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 2,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 2,
                    'Blue Plastic Cap' => 2,
                    'Label' => 2,
                    'Stretchfilm' => 2,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 13
            [
                'id' => 13,
                'product_name' => '350ml',
                'quantity' => 2,
                'qty_350ml' => 2,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-691',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 2,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 2,
                    'Blue Plastic Cap' => 2,
                    'Label' => 2,
                    'Stretchfilm' => 2,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 14
            [
                'id' => 14,
                'product_name' => '350ml',
                'quantity' => 5,
                'qty_350ml' => 5,
                'qty_500ml' => 0,
                'qty_1l' => 0,
                'qty_6l' => 0,
                'batch_number' => 'BATCH-20251109-791',
                'production_date' => '2025-11-09 00:00:00+08',
                'quantity_pcs' => 5,
                'materials_needed' => json_encode([
                    'Plastic Bottle (350ml)' => 5,
                    'Blue Plastic Cap' => 5,
                    'Label' => 5,
                    'Stretchfilm' => 5,
                ]),
                'selected_suppliers' => json_encode([
                    'Plastic Bottle (350ml)' => 1,
                    'Blue Plastic Cap' => 1,
                    'Label' => 3,
                    'Stretchfilm' => 5,
                ]),
                'employee_id' => 'E072501',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
