<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PurchaseOrderItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('purchase_order_items')->insert([
            [
                'id' => 1,
                'purchase_order_id' => 1,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 500,
                'received_quantity' => 250,
                'created_at' => '2025-11-03 00:51:45',
                'updated_at' => '2025-11-03 00:51:57',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 2,
                'purchase_order_id' => 2,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 100000,
                'received_quantity' => 100000,
                'created_at' => '2025-11-03 19:39:17',
                'updated_at' => '2025-11-03 19:41:17',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 3,
                'purchase_order_id' => 2,
                'item_name' => 'Plastic Bottle (500ml)',
                'item_type' => 'finished',
                'quantity' => 50000,
                'received_quantity' => 50000,
                'created_at' => '2025-11-03 19:39:18',
                'updated_at' => '2025-11-03 19:41:18',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 4,
                'purchase_order_id' => 3,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 1000,
                'received_quantity' => 1000,
                'created_at' => '2025-11-03 22:36:30',
                'updated_at' => '2025-11-03 22:37:38',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 5,
                'purchase_order_id' => 4,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 100,
                'received_quantity' => 100,
                'created_at' => '2025-11-04 15:51:37',
                'updated_at' => '2025-11-04 15:53:08',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 6,
                'purchase_order_id' => 5,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 100,
                'received_quantity' => 100,
                'created_at' => '2025-11-04 23:30:38',
                'updated_at' => '2025-11-04 23:30:47',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 7,
                'purchase_order_id' => 6,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 20,
                'received_quantity' => 20,
                'created_at' => '2025-11-04 23:43:48',
                'updated_at' => '2025-11-04 23:43:54',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 8,
                'purchase_order_id' => 7,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 2,
                'received_quantity' => 2,
                'created_at' => '2025-11-04 23:45:05',
                'updated_at' => '2025-11-04 23:45:11',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 9,
                'purchase_order_id' => 8,
                'item_name' => 'Plastic Bottle (500ml)',
                'item_type' => 'finished',
                'quantity' => 15,
                'received_quantity' => 15,
                'created_at' => '2025-11-05 00:06:05',
                'updated_at' => '2025-11-05 00:07:50',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 10,
                'purchase_order_id' => 9,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 4,
                'received_quantity' => 0,
                'created_at' => '2025-11-05 00:06:33',
                'updated_at' => '2025-11-05 00:06:33',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 11,
                'purchase_order_id' => 10,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 20,
                'received_quantity' => 20,
                'created_at' => '2025-11-05 00:14:35',
                'updated_at' => '2025-11-05 00:14:50',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 12,
                'purchase_order_id' => 11,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 54,
                'received_quantity' => 54,
                'created_at' => '2025-11-05 00:29:57',
                'updated_at' => '2025-11-05 00:30:09',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 13,
                'purchase_order_id' => 12,
                'item_name' => 'Plastic Bottle (350ml)',
                'item_type' => 'finished',
                'quantity' => 100,
                'received_quantity' => 100,
                'created_at' => '2025-11-09 12:30:13',
                'updated_at' => '2025-11-09 12:30:38',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
            [
                'id' => 14,
                'purchase_order_id' => 13,
                'item_name' => 'Plastic Bottle (500ml)',
                'item_type' => 'finished',
                'quantity' => 100,
                'received_quantity' => 100,
                'created_at' => '2025-11-09 18:23:56',
                'updated_at' => '2025-11-09 18:24:04',
                'unit_cost' => 0.00,
                'total_amount' => 0.00,
            ],
        ]);
    }
}
