<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SalesOrdersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('sales_orders')->insert([

            [
                'id' => 12,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-01-01',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)']),
                'delivery_date' => '2025-01-08',
                'order_type' => 'Standard Order',
                'amount' => 7650.00,
                'created_at' => '2025-11-04 20:40:59',
                'updated_at' => '2025-11-04 20:43:14',
                'quantities' => json_encode(['Bottled Water (1L)' => 10, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 25, 'Bottled Water (500ml)' => 20]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2024-01-02',
                'employee_id' => null,
            ],
            [
                'id' => 13,
                'location' => 'P1 Block 25 Lot 25, Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-01-01',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-01-08',
                'order_type' => 'Standard Order',
                'amount' => 7600.00,
                'created_at' => '2025-11-04 20:44:23',
                'updated_at' => '2025-11-04 20:44:33',
                'quantities' => json_encode(['Bottled Water (1L)' => 10, 'Gallon Water (6L)' => 10, 'Bottled Water (350ml)' => 20, 'Bottled Water (500ml)' => 20]),
                'customer_id' => 1,
                'status' => 'Delivered',
                'date_delivered' => '2024-01-02',
                'employee_id' => null,
            ],
            [
                'id' => 14,
                'location' => 'Katapatan Subdivision, Brgy. Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-01-02',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-01-09',
                'order_type' => 'CSO',
                'amount' => 42700.00,
                'created_at' => '2025-11-04 20:45:46',
                'updated_at' => '2025-11-04 20:45:57',
                'quantities' => json_encode(['Bottled Water (1L)' => 100, 'Gallon Water (6L)' => 20, 'Bottled Water (350ml)' => 100, 'Bottled Water (500ml)' => 100]),
                'customer_id' => 3,
                'status' => 'Delivered',
                'date_delivered' => '2024-01-03',
                'employee_id' => null,
            ],
            [
                'id' => 15,
                'location' => 'Banay-banay Road, Cabuyao City, Laguna',
                'date' => '2025-01-04',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-01-08',
                'order_type' => 'Standard Order',
                'amount' => 1300.00,
                'created_at' => '2025-11-04 20:47:32',
                'updated_at' => '2025-11-04 20:47:47',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 10, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 5,
                'status' => 'Delivered',
                'date_delivered' => '2025-01-07',
                'employee_id' => null,
            ],
            [
                'id' => 16,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-01-05',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)']),
                'delivery_date' => '2025-01-12',
                'order_type' => 'Standard Order',
                'amount' => 23350.00,
                'created_at' => '2025-11-04 20:50:40',
                'updated_at' => '2025-11-04 20:50:56',
                'quantities' => json_encode(['Bottled Water (1L)' => 20, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 100, 'Bottled Water (500ml)' => 50]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-01-07',
                'employee_id' => null,
            ],
            [
                'id' => 17,
                'location' => 'Matulungin St., Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-01-06',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)']),
                'delivery_date' => '2025-01-06',
                'order_type' => 'CSO',
                'amount' => 2075.00,
                'created_at' => '2025-11-04 20:51:51',
                'updated_at' => '2025-11-04 20:52:18',
                'quantities' => json_encode(['Bottled Water (1L)' => 5, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 5, 'Bottled Water (500ml)' => 5]),
                'customer_id' => 6,
                'status' => 'Delivered',
                'date_delivered' => '2025-01-07',
                'employee_id' => null,
            ],
            [
                'id' => 18,
                'location' => 'P1 Block 25 Lot 1 Lakesidenest Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-01-07',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)']),
                'delivery_date' => '2025-01-14',
                'order_type' => 'Standard Order',
                'amount' => 830.00,
                'created_at' => '2025-11-04 20:53:18',
                'updated_at' => '2025-11-04 20:53:28',
                'quantities' => json_encode(['Bottled Water (1L)' => 2, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 2, 'Bottled Water (500ml)' => 2]),
                'customer_id' => 4,
                'status' => 'Delivered',
                'date_delivered' => '2025-01-07',
                'employee_id' => null,
            ],
            [
                'id' => 19,
                'location' => 'Katapatan Subdivision, Brgy. Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-02-01',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-02-08',
                'order_type' => 'Standard Order',
                'amount' => 179085.00,
                'created_at' => '2025-11-04 20:54:46',
                'updated_at' => '2025-11-04 20:54:59',
                'quantities' => json_encode(['Bottled Water (1L)' => 350, 'Gallon Water (6L)' => 20, 'Bottled Water (350ml)' => 452, 'Bottled Water (500ml)' => 475]),
                'customer_id' => 3,
                'status' => 'Delivered',
                'date_delivered' => '2025-02-01',
                'employee_id' => null,
            ],
            [
                'id' => 20,
                'location' => 'P1 Block 25 Lot 25, Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-03-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-03-11',
                'order_type' => 'Standard Order',
                'amount' => 134020.00,
                'created_at' => '2025-11-04 20:55:59',
                'updated_at' => '2025-11-04 20:56:09',
                'quantities' => json_encode(['Bottled Water (1L)' => 266, 'Gallon Water (6L)' => 62, 'Bottled Water (350ml)' => 350, 'Bottled Water (500ml)' => 324]),
                'customer_id' => 1,
                'status' => 'Delivered',
                'date_delivered' => '2025-03-04',
                'employee_id' => null,
            ],
            [
                'id' => 21,
                'location' => 'P1 Block 25 Lot 1 Lakesidenest Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-04-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-04-11',
                'order_type' => 'Standard Order',
                'amount' => 272925.00,
                'created_at' => '2025-11-04 20:57:28',
                'updated_at' => '2025-11-04 20:57:39',
                'quantities' => json_encode(['Bottled Water (1L)' => 592, 'Gallon Water (6L)' => 120, 'Bottled Water (350ml)' => 652, 'Bottled Water (500ml)' => 671]),
                'customer_id' => 4,
                'status' => 'Delivered',
                'date_delivered' => '2025-04-04',
                'employee_id' => null,
            ],
            [
                'id' => 22,
                'location' => 'Katapatan Subdivision, Brgy. Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-05-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-05-11',
                'order_type' => 'Standard Order',
                'amount' => 322570.00,
                'created_at' => '2025-11-04 20:58:23',
                'updated_at' => '2025-11-04 20:58:31',
                'quantities' => json_encode(['Bottled Water (1L)' => 620, 'Gallon Water (6L)' => 216, 'Bottled Water (350ml)' => 865, 'Bottled Water (500ml)' => 752]),
                'customer_id' => 3,
                'status' => 'Delivered',
                'date_delivered' => '2025-04-04',
                'employee_id' => null,
            ],
            [
                'id' => 23,
                'location' => 'Banay-banay Road, Cabuyao City, Laguna',
                'date' => '2025-06-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-06-11',
                'order_type' => 'CSO',
                'amount' => 251125.00,
                'created_at' => '2025-11-04 20:59:07',
                'updated_at' => '2025-11-04 20:59:18',
                'quantities' => json_encode(['Bottled Water (1L)' => 466, 'Gallon Water (6L)' => 130, 'Bottled Water (350ml)' => 620, 'Bottled Water (500ml)' => 659]),
                'customer_id' => 5,
                'status' => 'Delivered',
                'date_delivered' => '2025-06-04',
                'employee_id' => null,
            ],
            [
                'id' => 24,
                'location' => 'Matulungin St., Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-07-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-07-04',
                'order_type' => 'Standard Order',
                'amount' => 210170.00,
                'created_at' => '2025-11-04 21:00:54',
                'updated_at' => '2025-11-04 21:01:01',
                'quantities' => json_encode(['Bottled Water (1L)' => 459, 'Gallon Water (6L)' => 90, 'Bottled Water (350ml)' => 520, 'Bottled Water (500ml)' => 500]),
                'customer_id' => 6,
                'status' => 'Delivered',
                'date_delivered' => '2025-07-04',
                'employee_id' => null,
            ],
            [
                'id' => 25,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-08-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-08-11',
                'order_type' => 'Standard Order',
                'amount' => 181905.00,
                'created_at' => '2025-11-04 21:02:47',
                'updated_at' => '2025-11-04 21:02:53',
                'quantities' => json_encode(['Bottled Water (1L)' => 230, 'Gallon Water (6L)' => 60, 'Bottled Water (350ml)' => 580, 'Bottled Water (500ml)' => 471]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-08-04',
                'employee_id' => null,
            ],
            [
                'id' => 26,
                'location' => 'Banay-banay Road, Cabuyao City, Laguna',
                'date' => '2025-09-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-09-11',
                'order_type' => 'CSO',
                'amount' => 163355.00,
                'created_at' => '2025-11-04 21:03:21',
                'updated_at' => '2025-11-04 21:03:29',
                'quantities' => json_encode(['Bottled Water (1L)' => 200, 'Gallon Water (6L)' => 50, 'Bottled Water (350ml)' => 460, 'Bottled Water (500ml)' => 481]),
                'customer_id' => 5,
                'status' => 'Delivered',
                'date_delivered' => '2025-09-04',
                'employee_id' => null,
            ],
            [
                'id' => 27,
                'location' => 'P1 Block 25 Lot 25, Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-10-04',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)', 'Gallon Water (6L)']),
                'delivery_date' => '2025-10-11',
                'order_type' => 'CSO',
                'amount' => 225915.00,
                'created_at' => '2025-11-04 21:03:56',
                'updated_at' => '2025-11-04 21:04:06',
                'quantities' => json_encode(['Bottled Water (1L)' => 428, 'Gallon Water (6L)' => 61, 'Bottled Water (350ml)' => 577, 'Bottled Water (500ml)' => 591]),
                'customer_id' => 1,
                'status' => 'Delivered',
                'date_delivered' => '2025-10-04',
                'employee_id' => null,
            ],
            [
                'id' => 28,
                'location' => 'Matulungin St., Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-11-01',
                'products' => json_encode(['Bottled Water (350ml)', 'Bottled Water (500ml)', 'Bottled Water (1L)']),
                'delivery_date' => '2025-11-08',
                'order_type' => 'CSO',
                'amount' => 7000.00,
                'created_at' => '2025-11-04 21:04:29',
                'updated_at' => '2025-11-04 21:04:36',
                'quantities' => json_encode(['Bottled Water (1L)' => 10, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 20, 'Bottled Water (500ml)' => 20]),
                'customer_id' => 6,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-04',
                'employee_id' => null,
            ],
            [
                'id' => 29,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-11-04',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-04',
                'order_type' => 'Standard Order',
                'amount' => 520.00,
                'created_at' => '2025-11-04 23:27:10',
                'updated_at' => '2025-11-04 23:27:35',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 4, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-04',
                'employee_id' => null,
            ],
            [
                'id' => 31,
                'location' => 'P1 Block 25 Lot 25, Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-11-05',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-05',
                'order_type' => 'Standard Order',
                'amount' => 260.00,
                'created_at' => '2025-11-05 00:34:16',
                'updated_at' => '2025-11-05 00:34:25',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 2, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 1,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-05',
                'employee_id' => null,
            ],
            [
                'id' => 32,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-11-05',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-05',
                'order_type' => 'Standard Order',
                'amount' => 130.00,
                'created_at' => '2025-11-05 00:35:30',
                'updated_at' => '2025-11-05 00:35:30',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 1, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 2,
                'status' => 'Pending',
                'date_delivered' => null,
                'employee_id' => null,
            ],
            [
                'id' => 33,
                'location' => 'Matulungin St., Katapatan Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-11-05',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-05',
                'order_type' => 'Standard Order',
                'amount' => 130.00,
                'created_at' => '2025-11-05 00:46:13',
                'updated_at' => '2025-11-05 00:46:13',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 1, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 6,
                'status' => 'Pending',
                'date_delivered' => null,
                'employee_id' => null,
            ],
            [
                'id' => 34,
                'location' => 'P1 Block 25 Lot 1 Lakesidenest Subdivision, Barangay Banay-banay, Cabuyao City, Laguna',
                'date' => '2025-11-05',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-05',
                'order_type' => 'Standard Order',
                'amount' => 8970.00,
                'created_at' => '2025-11-05 00:48:17',
                'updated_at' => '2025-11-05 00:48:29',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 69, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 4,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-05',
                'employee_id' => null,
            ],
            [
                'id' => 35,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-11-06',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-06',
                'order_type' => 'Standard Order',
                'amount' => 130.00,
                'created_at' => '2025-11-05 10:09:38',
                'updated_at' => '2025-11-05 10:09:45',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 1, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-06',
                'employee_id' => null,
            ],
            [
                'id' => 36,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-11-08',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-08',
                'order_type' => 'Standard Order',
                'amount' => 130.00,
                'created_at' => '2025-11-08 22:45:03',
                'updated_at' => '2025-11-08 22:45:38',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 1, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-08',
                'employee_id' => null,
            ],
            [
                'id' => 37,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-11-09',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-09',
                'order_type' => 'Standard Order',
                'amount' => 130.00,
                'created_at' => '2025-11-09 12:20:51',
                'updated_at' => '2025-11-09 12:21:01',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 1, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-09',
                'employee_id' => null,
            ],
            [
                'id' => 38,
                'location' => 'Lakesidenest Subdivision Branch',
                'date' => '2025-11-09',
                'products' => json_encode(['Bottled Water (350ml)']),
                'delivery_date' => '2025-11-09',
                'order_type' => 'Standard Order',
                'amount' => 130.00,
                'created_at' => '2025-11-09 12:24:50',
                'updated_at' => '2025-11-09 12:25:01',
                'quantities' => json_encode(['Bottled Water (1L)' => 0, 'Gallon Water (6L)' => 0, 'Bottled Water (350ml)' => 1, 'Bottled Water (500ml)' => 0]),
                'customer_id' => 2,
                'status' => 'Delivered',
                'date_delivered' => '2025-11-09',
                'employee_id' => null,
            ],
        ]);
    }
}
      